# Generated by Django 5.0.3 on 2024-03-08 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pc',
            name='data',
        ),
        migrations.AddField(
            model_name='pc',
            name='temperatura',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='pc',
            name='uso_CPU',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='pc',
            name='uso_RAM',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
