# Generated by Django 5.0.3 on 2024-03-09 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_pc_data_pc_temperatura_pc_uso_cpu_pc_uso_ram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pc',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='pc',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='pc',
            name='temperatura',
        ),
        migrations.RemoveField(
            model_name='pc',
            name='uso_CPU',
        ),
        migrations.RemoveField(
            model_name='pc',
            name='uso_RAM',
        ),
        migrations.CreateModel(
            name='Dados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('uso_CPU', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('uso_RAM', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dados', to='backend.pc')),
            ],
        ),
    ]
