# Generated by Django 5.0.3 on 2024-03-09 00:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_pc_created_at_remove_pc_modified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados',
            name='data_recebimento',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
