# Generated by Django 4.2.13 on 2024-07-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_dados_data_recebimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pc',
            name='power',
            field=models.BooleanField(default=False),
        ),
    ]
