# Generated by Django 5.0.14 on 2026-04-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_pc_power'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pc',
            old_name='power',
            new_name='update',
        ),
        migrations.AddField(
            model_name='pc',
            name='mode_fan',
            field=models.IntegerField(choices=[(0, 'Desligado'), (1, 'Ligado'), (2, 'Automático')], default=0),
        ),
    ]
